### ISSUE TITLE
[Request] Command do delete gif/packs

### ISSUE THREAD

**Issue by edcaron** [yi-jiayu/saved-gifs-bot#1]
It would be great if the bot had the possibility to remove gif or packs.

**Comment by yi-jiayu** [comment]
Hello! Cool, I haven't touched this for a while and didn't realise anyone was using it.

That makes sense, it's a feature which should have been inside from the start. I'll look into it!

**Comment by Takuma-The-Akai-Kage** [comment]
A delete function too remove gifs would be great :)

**Comment by yi-jiayu** [comment]
Added a `/deletepack` command to delete gif packs, and added the previously undocumented `/deletegif` command to the list of commands on Telegram. 

Hope it works, do report any bugs or unexpected behavior you run into!
